
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    # ticket by johnyu-------------------------------------start

    # front 服务地址
	upstream wsmp-front-server {
        server 127.0.0.1:10377     max_fails=2     fail_timeout=120s; # sit
	}
    
    server{
		listen	9376	default_server;
        server_name	localhost;

		location /ticket/wsmp-front/ {
			proxy_pass http://wsmp-front-server/wsmp-front/; # front 服务地址
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_connect_timeout 40;
		}

        location /ticket {
            alias /data/app/ticket/;
            index index.html index.htm;
            # HTML 文件的缓存配置
            location ~* \.(htm|html)$ {
                add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Strict-Transport-Security "max-age=31536000" always;
            }
            try_files $uri $uri/ /ticket/index.html;
        }

    }

    # ticket by johnyu-------------------------------------end

}
