
    # ticket by johnyu-------------------------------------start

    # front 服务地址
	upstream wsmp-front-server {
        server [#WSMP_FRONT_ADD]     max_fails=2     fail_timeout=120s; # sit
	}
    
    server{
		listen	9373	default_server;
        server_name	[#WSMP_FR_SERVER];

		location /ticket/wsmp-front/ {
			proxy_pass http://wsmp-front-server/wsmp-front/; # front 服务地址
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_connect_timeout 40;
		}

        location /ticket {
            alias /data/app/ticket/;
            index index.html index.htm;
            # HTML 文件的缓存配置
            location ~* \.(htm|html)$ {
                add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Strict-Transport-Security "max-age=31536000" always;
            }
            try_files $uri $uri/ /ticket/index.html;
        }

    }

    # ticket by johnyu-------------------------------------end
